## 리스트와는 다르다: ndarray 생성하기

NumPy의 핵심 객체는 ndarray (N-dimensional Array)다.

파이썬 리스트와 비슷해 보이지만, "모든 원소가 같은 자료형(Type)이어야 한다"는 철칙이 있다.

In [1]:
import numpy as np

# 1. 리스트를 변환하여 생성
data = [1, 2, 3, 4, 5]
arr = np.array(data)
print(arr)  # [1 2 3 4 5]  (쉼표가 없다!)

# 2. 특수한 배열 생성 함수들
print(np.zeros(5))        # [0. 0. 0. 0. 0.] -> 0으로 채움
print(np.ones((2, 3)))    # 1로 채운 2x3 행렬
print(np.arange(1, 10, 2))# [1 3 5 7 9] -> range()와 동일한 기능


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]


## 데이터 타입(dtype)이 중요한 이유

파이썬 리스트는 정수, 실수, 문자열을 마구 섞어 담을 수 있지만, NumPy는 효율성을 위해 타입을 엄격히 제한한다.

* int (정수): int8, int16, int32, int64
* float (실수): float16, float32, float64
* bool (논리): True, False

In [2]:
arr_float = np.array([1, 2, 3], dtype=float) # 강제로 실수형으로 생성
print(arr_float.dtype) # float64

arr_int = arr_float.astype(int) # 형 변환 (Casting)
print(arr_int.dtype)   # int32 or int64


float64
int64


> [Tip] 딥러닝에서는 메모리를 아끼기 위해 float64 대신 float32를 주로 사용합니다. dtype을 확인하고 변환하는 습관은 대용량 데이터 처리의 첫걸음입니다.

In [4]:
bool_arr = np.array([0, 1, 2], dtype=bool) # 0은 False, 나머지는 True
print(bool_arr) # [False  True  True]

print(bool_arr.dtype) # bool

[False  True  True]
bool


## 배열의 산술 연산

리스트에서 [1, 2] + [3, 4]를 하면 [1, 2, 3, 4]로 이어 붙여지지만, NumPy에서는 같은 위치의 요소끼리 더해진다(Element-wise). 이것이 수학적인 벡터 연산이다.

In [5]:
a = np.array([1, 16, 81])
b = np.array([2, 5, 100])

# 1. 사칙 연산 (위치끼리 계산)
print(a + b)      # [3 21 181]
print(a * b)      # [2 80 8100]

# 2. 브로드캐스팅 (스칼라 연산)
print(a + 10)     # [11 26 91] -> 모든 원소에 10 더하기

# 3. 거듭제곱 (Power)
# 0.5승은 제곱근(Root), 0.25승은 4제곱근을 의미
print(a ** 0.5)   # [1. 4. 9.]  -> sqrt(a)와 동일
print(a ** 0.25)  # [1. 2. 3.]

# 4. 비교 연산 (Comparison) -> 불리언 배열 반환
# 결과가 True/False로 구성된 배열로 나옵니다.
print(a > b)      # [False True False]
# 해석: 1>2(거짓), 16>5(참), 81>100(거짓)


[  3  21 181]
[   2   80 8100]
[11 26 91]
[1. 4. 9.]
[1. 2. 3.]
[False  True False]


여기서 a > b의 결과로 나온 [False, True, False] 같은 불리언 배열은 다음 절에서 배울 데이터 필터링(불리언 인덱싱)의 핵심 재료가 된다.

데이터 분석을 하다 보면 값이 비어있는 '결측치'를 자주 마주합니다. 파이썬 데이터 생태계에서는 이를 np.nan (Not a Number)으로 표시합니다.

그런데 아주 중요한 사실이 있습니다. np.nan의 자료형은 '실수(float)'입니다.

NumPy는 자료형을 엄격하게 지키기 때문에, 정수(int)로만 이루어진 배열에는 실수인 np.nan을 집어넣을 수 없습니다.

In [7]:
import numpy as np

# 1. 정수 배열 생성
arr = np.array([1, 2, 3]) # dtype='int'

# 2. 결측치 대입 시도 -> 에러 발생!
arr[0] = np.nan 
# ValueError: cannot convert float NaN to integer


ValueError: cannot convert float NaN to integer

따라서 데이터에 결측치가 하나라도 포함될 가능성이 있다면, 그 배열은 반드시 `float` (실수형)이어야 합니다. read_csv로 데이터를 불러올 때, 멀쩡해 보이는 정수 칼럼이 float로 변환되어 있다면 "아, 중간에 결측치가 있구나!"라고 짐작하면 됩니다.