## 기본 인덱싱과 슬라이싱

In [2]:
import numpy as np

arr = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]

# 인덱싱 (위치로 꺼내기)
print(arr[5])    # 5
print(arr[-1])   # 9 (맨 끝)

# 슬라이싱 (범위로 자르기) [시작:끝]
print(arr[5:8])  # [5 6 7] (8번 인덱스 미포함)
print(arr[:3])   # [0 1 2] (처음부터 3번 전까지)


5
9
[5 6 7]
[0 1 2]


## [핵심] 불리언 인덱싱 (Boolean Indexing)

데이터 분석에서 가장 많이 쓰는 기능이다. "값이 5보다 큰 것만 가져와"와 같이 조건(Condition)을 주어 데이터를 필터링한다.

In [3]:
## [예제 1]
names = np.array(["Alice", "Bob", "Charlie", "Alice"])
data = np.random.randn(4, 4) # 4x4 난수 행렬

# 1. 조건 생성 (True/False 배열 반환)
is_alice = (names == "Alice")
print(is_alice) # [True, False, False, True]

# 2. 필터링 (True인 위치의 데이터만 꺼냄)
print(data[is_alice])

## [예제 2]
arr = np.array([10,20,30,40])
mask = arr > 25

# 25보다 큰 값만 True
print(mask) # [False False  True  True]

# mask의 값이 True인 값을 필터링
filtered = arr[mask]
print(filtered)  # [30, 40]


[ True False False  True]
[[ 0.17263531  1.03335574  0.08761675  0.54732677]
 [-0.30359706  0.36964706 -0.89738111  0.05936547]]
[False False  True  True]
[30 40]


In [4]:
data

array([[ 0.17263531,  1.03335574,  0.08761675,  0.54732677],
       [-0.98740274, -1.79373417, -0.28020302,  1.87304387],
       [ 1.13257077,  0.25097857,  2.14255201,  0.34237911],
       [-0.30359706,  0.36964706, -0.89738111,  0.05936547]])

파이썬 리스트와 달리, NumPy 배열을 슬라이싱할 때는 매우 조심해야 합니다.

NumPy는 대용량 데이터를 다루기 때문에, 슬라이싱을 할 때마다 데이터를 새로 복사하면 메모리 낭비가 심합니다. 그래서 NumPy는 데이터를 복사하지 않고, 원본을 그대로 바라보는 '뷰(View)'를 반환합니다.

즉, 잘라낸 조각을 수정하면 원본 데이터도 같이 바뀝니다.

In [5]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4])
piece = arr[0:2]  # [0, 1]을 잘라냄 (뷰 생성)

piece[0] = 999    # 잘라낸 조각을 수정했는데...
print(arr)        # [999, 1, 2, 3, 4] -> 헉! 원본도 바뀌었다!


[999   1   2   3   4]


이런 사고를 방지하려면, 원본과 별개로 데이터를 쓰고 싶을 때 반드시 .copy() 메서드를 사용해야 합니다.

In [7]:
arr = np.arange(5) # [0, 1, 2, 3, 4]
piece = arr[0:2].copy()

piece[0] = 999
print(arr) # [0, 1, 2, 3, 4] -> 원본은 안전!

[0 1 2 3 4]
