## 통계 함수 (Statistics)

NumPy는 배열 전체 혹은 특정 축(Axis)에 대한 강력한 통계 함수를 제공한다.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 100]) # 100은 이상치(Outlier)

print(f"합계: {np.sum(arr)}")        # 115
print(f"평균: {np.mean(arr)}")       # 19.16...
print(f"분산: {np.var(arr):.2f}")    # 1094.14 (데이터가 퍼진 정도)
print(f"표준편차: {np.std(arr):.2f}")# 33.08
print(f"최솟값: {np.min(arr)}")      # 1
print(f"최댓값: {np.max(arr)}")      # 100
print(f"최댓값 위치: {np.argmax(arr)}") # 5 (인덱스 반환)

# 백분위수 (Percentile): 하위 50%(중앙값)와 25%(1사분위수) 구하기
print(f"중앙값(50%): {np.median(arr)}")     # 3.5
print(f"하위 25%: {np.percentile(arr, 25)}") # 2.25


합계: 115
평균: 19.166666666666668
분산: 1308.47
표준편차: 36.17
최솟값: 1
최댓값: 100
최댓값 위치: 5
중앙값(50%): 3.5
하위 25%: 2.25


## 난수 생성 (Random Number Generation)

np.random 모듈은 데이터 과학의 필수품이다. 단순히 랜덤한 숫자를 만드는 것을 넘어, 데이터를 섞거나(Shuffle) 일부를 뽑는(Choice) 기능이 핵심이다.

* seed(n): 시드 고정 (실험 재현성을 위해 필수)
* rand(n): 0~1 사이 균등 분포
* randn(n): 표준정규분포(평균0, 분산1)
* randint(low, high, size): 정수 난수 생성

In [7]:
np.random.seed(42)

# 1. 무작위 섞기 (Shuffle) - 원본을 바꿈!
items = np.arange(10)
np.random.shuffle(items)
print(f"섞인 결과: {items}")

# 2. 임의 추출 (Choice) - 로또 번호 뽑기 등에 활용
# replace=False: 비복원 추출 (한 번 뽑은 건 다시 안 뽑음)
lotto = np.random.choice(range(1, 46), 6, replace=False)
print(f"로또 번호: {lotto}")


섞인 결과: [8 1 5 0 7 2 9 4 3 6]
로또 번호: [20 42  8 13 44  6]


## 정렬(Sort)과 집합(Set) 연산

데이터를 크기순으로 나열하거나, 두 데이터셋 간의 교집합(공통 고객), 차집합(이탈 고객) 등을 구할 때 사용한다.

#### 1. 정렬 (Sort)

np.sort(arr) 혹은 arr.sort()에 의해 배열에 대한 정렬 가능하다.

* `np.sort(arr)` : 원본 배열은 그대로 두고, 정렬된 복사본을 반환한다.
* `arr.sort()` : 원본 배열 자체를 직접 정렬(in-place) 한다. 반환값은 None이며 복사를 하지 않기에 메모리 효율이 좋다.

In [8]:
arr = np.array([3, 1, 5, 2, 4])

# 복사본 생성 정렬
sorted_arr = np.sort(arr)
print(arr)         # [3, 1, 5, 2, 4] (원본 유지)
print(sorted_arr)  # [1, 2, 3, 4, 5]

# 원본 직접 정렬
arr.sort()
print(arr)         # [1, 2, 3, 4, 5] (원본 변경)


[3 1 5 2 4]
[1 2 3 4 5]
[1 2 3 4 5]


### 오름차순 vs. 내림차순

정렬할 때 디폴트는 오름차순(Ascending)이다. 내림차순(Descending)으로 정렬할 때는 배열의 '슬라이싱' 기법인 [::-1]을 이용한다.

In [9]:
arr = np.array([3, 1, 5, 2, 4])

# 오름차순 정렬 (Default)
asc_arr = np.sort(arr)
print(asc_arr)     # [1, 2, 3, 4, 5]

# 내림차순 정렬 (Slicing 활용)
desc_arr = np.sort(arr)[::-1]
print(desc_arr)    # [5, 4, 3, 2, 1]


[1 2 3 4 5]
[5 4 3 2 1]


### 정렬된 인덱스 (np.argsort())

`np.argsort(arr)`는 실제 배열을 정렬된 순서로 바꾸지는 않고 "정렬되었을 때의 인덱스"를 반환한다. 이러한 특성으로 데이터 사이언스에서 자주 쓰인다.

예를 들어 '학생 이름' 배열과 '점수' 배열이 있을 때, 점수가 높은 순서대로의 '이름'을 알고 싶다고하면, np.argsort()를 이용해서 '점수'에 의해 정렬되었을 때의 인덱스를 알면, 이를 이용해서 정렬된 '이름'을 알 수 있다.

In [10]:
import numpy as np

# 데이터 준비 (서로 연결된 정보)
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
scores = np.array([85, 95, 70, 88])

# 1. 점수를 기준으로 정렬했을 때의 '인덱스'를 구함
# 오름차순 인덱스: [2, 0, 3, 1] (70점, 85점, 88점, 95점 순서의 원래 위치)
# 내림차순(높은 순)으로 변환
sorted_idx = np.argsort(scores)[::-1] 

print(f"정렬 순서 리모컨(인덱스): {sorted_idx}")
# 결과: [1, 3, 0, 2] (Bob, David, Alice, Charlie 순서)

# 2. 얻은 인덱스를 사용하여 이름 배열을 팬시 인덱싱(Fancy Indexing)함
sorted_names = names[sorted_idx]
sorted_scores = scores[sorted_idx]

print(f"성적 우수자 명단: {sorted_names}")
print(f"성적 우수자 점수: {sorted_scores}")


정렬 순서 리모컨(인덱스): [1 3 0 2]
성적 우수자 명단: ['Bob' 'David' 'Alice' 'Charlie']
성적 우수자 점수: [95 88 85 70]


### 2. 집합 연산 (Set Operations) [실무 추천]

1차원 배열을 집합(Set)으로 간주하고 연산을 수행한다. ID 매칭에 아주 유용하다.

In [12]:
cust_A = np.array([1, 2, 3, 4]) # 지난달 구매 고객
cust_B = np.array([3, 4, 5, 6]) # 이번달 구매 고객

# 1. 중복 제거 (Unique)
print(np.unique([1, 1, 2, 2, 3])) # [1 2 3]

# 2. 교집합 (Intersect): 두 달 연속 구매한 충성 고객
print(np.intersect1d(cust_A, cust_B)) # [3 4]

# 3. 합집합 (Union): 한 번이라도 구매한 전체 고객
print(np.union1d(cust_A, cust_B)) # [1 2 3 4 5 6]

# 4. 차집합 (Set Difference): 지난달엔 샀는데 이번엔 안 산(이탈) 고객
# (A - B)
print(np.setdiff1d(cust_A, cust_B)) # [1 2]

# 5. 포함 여부 확인 (Membership): cust_A가 cust_B에 포함되는가?
# 결과는 불리언 배열로 나옴
print(np.isin(cust_A, cust_B)) # [False False  True  True]


[1 2 3]
[3 4]
[1 2 3 4 5 6]
[1 2]
[False False  True  True]
